#!/usr/bin/env node
/**
 * Design Token Exporter
 * Converts JSON tokens → CSS variables + Tailwind config automatically
 * Usage: node export-tokens.js [tokens.json] [--out-css output.css] [--out-tw tailwind.tokens.js]
 */

const fs = require('fs');
const path = require('path');

const INPUT      = process.argv[2] || 'tokens.json';
const OUT_CSS    = process.argv.includes('--out-css') ? process.argv[process.argv.indexOf('--out-css') + 1] : 'src/tokens.css';
const OUT_TW     = process.argv.includes('--out-tw')  ? process.argv[process.argv.indexOf('--out-tw') + 1]  : 'tailwind.config.tokens.js';

if (!fs.existsSync(INPUT)) {
  console.error(`❌ Token file not found: ${INPUT}`);
  console.error('Usage: node export-tokens.js tokens.json [--out-css src/tokens.css] [--out-tw tailwind.config.tokens.js]');
  process.exit(1);
}

const raw = JSON.parse(fs.readFileSync(INPUT, 'utf8'));

// --- Flatten tokens ---
function flatten(obj, prefix = '') {
  const result = {};
  for (const [k, v] of Object.entries(obj)) {
    const key = prefix ? `${prefix}-${k}` : k;
    if (typeof v === 'string' || typeof v === 'number') result[key] = String(v);
    else if (typeof v === 'object' && v !== null) Object.assign(result, flatten(v, key));
  }
  return result;
}

const flat = flatten(raw);

// Separate by category
const colors    = Object.entries(flat).filter(([k]) => k.startsWith('color'));
const spacing   = Object.entries(flat).filter(([k]) => k.startsWith('spacing') || k.startsWith('space'));
const radius    = Object.entries(flat).filter(([k]) => k.startsWith('radius') || k.startsWith('border-radius'));
const shadow    = Object.entries(flat).filter(([k]) => k.startsWith('shadow'));
const motion    = Object.entries(flat).filter(([k]) => k.startsWith('motion') || k.startsWith('duration') || k.startsWith('easing'));
const typography = Object.entries(flat).filter(([k]) => k.startsWith('typography') || k.startsWith('font'));
const other     = Object.entries(flat).filter(([k]) => !colors.find(c => c[0] === k) && !spacing.find(s => s[0] === k) && !radius.find(r => r[0] === k) && !shadow.find(s => s[0] === k) && !motion.find(m => m[0] === k) && !typography.find(t => t[0] === k));

// --- Generate CSS ---
function toCSSVar(key) { return `--${key}`; }

function generateCSS(tokens, flat) {
  const colorEntries = colors.map(([k, v]) => `  ${toCSSVar(k)}: ${v};`).join('\n');
  const spacingEntries = spacing.map(([k, v]) => `  ${toCSSVar(k)}: ${v};`).join('\n');
  const radiusEntries = radius.map(([k, v]) => `  ${toCSSVar(k)}: ${v};`).join('\n');
  const shadowEntries = shadow.map(([k, v]) => `  ${toCSSVar(k)}: ${v};`).join('\n');
  const motionEntries = motion.map(([k, v]) => `  ${toCSSVar(k)}: ${v};`).join('\n');
  const typographyEntries = typography.map(([k, v]) => `  ${toCSSVar(k)}: ${v};`).join('\n');
  const otherEntries = other.map(([k, v]) => `  ${toCSSVar(k)}: ${v};`).join('\n');

  // Detect dark colors for dark mode block
  const darkColors = colors.filter(([k]) => k.includes('dark') || k.includes('night') || k.includes('bg-'));
  const darkBlock = darkColors.length
    ? `\n[data-theme="dark"] {\n${darkColors.map(([k, v]) => `  ${toCSSVar(k)}: ${v};`).join('\n')}\n}`
    : '';

  return `/* Auto-generated by export-tokens.js — DO NOT EDIT MANUALLY */
/* Source: ${INPUT} | Generated: ${new Date().toISOString()} */

:root {
${colorEntries ? `  /* Colors */\n${colorEntries}\n` : ''}
${spacingEntries ? `  /* Spacing */\n${spacingEntries}\n` : ''}
${radiusEntries ? `  /* Border Radius */\n${radiusEntries}\n` : ''}
${shadowEntries ? `  /* Shadows */\n${shadowEntries}\n` : ''}
${motionEntries ? `  /* Motion */\n${motionEntries}\n` : ''}
${typographyEntries ? `  /* Typography */\n${typographyEntries}\n` : ''}
${otherEntries ? `  /* Other */\n${otherEntries}` : ''}
}
${darkBlock}
`;
}

// --- Generate Tailwind config ---
function toTailwindKey(key) {
  return key
    .replace(/^color-/, '')
    .replace(/^spacing-/, '')
    .replace(/^radius-/, '')
    .replace(/^shadow-/, '')
    .replace(/^font-/, '')
    .replace(/-DEFAULT$/, '');
}

function generateTailwind(flat) {
  const twColors = {};
  const twSpacing = {};
  const twRadius = {};
  const twShadow = {};
  const twFontSize = {};
  const twFontFamily = {};

  for (const [k] of colors) {
    const tw = toTailwindKey(k);
    const parts = tw.split('-');
    if (parts.length === 1) {
      twColors[tw] = `var(${toCSSVar(k)})`;
    } else {
      const group = parts[0];
      const variant = parts.slice(1).join('-') || 'DEFAULT';
      if (!twColors[group]) twColors[group] = {};
      twColors[group][variant] = `var(${toCSSVar(k)})`;
    }
  }
  for (const [k] of spacing) twSpacing[toTailwindKey(k)] = `var(${toCSSVar(k)})`;
  for (const [k] of radius) twRadius[toTailwindKey(k)] = `var(${toCSSVar(k)})`;
  for (const [k] of shadow) twShadow[toTailwindKey(k)] = `var(${toCSSVar(k)})`;

  return `/* Auto-generated by export-tokens.js — DO NOT EDIT MANUALLY */
/* Source: ${INPUT} | Generated: ${new Date().toISOString()} */

/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: ${JSON.stringify(twColors, null, 6).replace(/"var\(/g, 'var(').replace(/\)"/g, ')')},
      spacing: ${JSON.stringify(twSpacing, null, 6).replace(/"var\(/g, 'var(').replace(/\)"/g, ')')},
      borderRadius: ${JSON.stringify(twRadius, null, 6).replace(/"var\(/g, 'var(').replace(/\)"/g, ')')},
      boxShadow: ${JSON.stringify(twShadow, null, 6).replace(/"var\(/g, 'var(').replace(/\)"/g, ')')},
    },
  },
};
`;
}

// --- Write files ---
const cssContent = generateCSS(flat);
const twContent = generateTailwind(flat);

fs.mkdirSync(path.dirname(OUT_CSS), { recursive: true });
fs.writeFileSync(OUT_CSS, cssContent);
fs.writeFileSync(OUT_TW, twContent);

console.log('\n' + '='.repeat(60));
console.log('DESIGN TOKEN EXPORTER');
console.log('='.repeat(60));
console.log(`Input:   ${INPUT}`);
console.log(`CSS:     ${OUT_CSS} (${Object.keys(flat).length} variables)`);
console.log(`Tailwind: ${OUT_TW}`);
console.log(`\nBreakdown:`);
console.log(`  Colors:     ${colors.length}`);
console.log(`  Spacing:    ${spacing.length}`);
console.log(`  Radius:     ${radius.length}`);
console.log(`  Shadow:     ${shadow.length}`);
console.log(`  Motion:     ${motion.length}`);
console.log(`  Typography: ${typography.length}`);
console.log(`  Other:      ${other.length}`);
console.log('\nSTATUS: DONE ✅');
console.log(`\nNext: @import "${OUT_CSS}" in your globals.css`);
console.log(`      Spread ${OUT_TW} into your tailwind.config.js`);
